paths:
  protein_file_path: "../data/protein_input_files/mpro_sarscov2.pdb"
  molmim_generated_csv: '../data/molmim_generated_molecules.csv'
  diffdock_output_dir: "../data/diffdock_outputs/"
  dsmbind_input_dir: "../data/dsmbind_inputs"
  starting_molecule_csv: '../data/starting_molecule_smiles.csv'
  dsmbind_predictions_csv: '../data/dsmbind_predictions.csv'
  results_csv: '../data/results.csv'

threshold_binding_affinity: -1400000
threshold_for_number_of_selected_molecules: 10
  